# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm6250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter joyeuse,$(TARGET_DEVICE)),)

endif
